apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: debezium-connector-progres
  namespace: kafka
  labels:
    strimzi.io/cluster: debezium-connect-cluster
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    tasks.max: 1
    database.hostname: postgresql.default.svc.cluster.local
    database.port: "5432"
    database.user: ${secrets:kafka/debezium-secret:username}
    database.password: ${secrets:kafka/debezium-secret:password}
    #database.dbname: feast
    topic.prefix: debezium
    database.include.list: feast
    schema.history.internal.kafka.bootstrap.servers: my-cluster-kafka-bootstrap:9092
    schema.history.internal.kafka.topic: schema-changes.feast