apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: sink-connector-progres
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-connect-sink-postgres-cluster
spec:
  class: io.confluent.connect.jdbc.JdbcSinkConnector
  tasksMax: 1
  config:
    topics: feast.public.titanic_survive_svc_v1
    tasks.max: 1
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.storage.StringConverter
    connection.url: jdbc:postgresql://postgresql.default.svc.cluster.local:5432/feast_online
    connection.user: ${secrets:kafka/postgresql-online-secret:username}
    connection.password: ${secrets:kafka/postgresql-online-secret:password}
    plugin.path: /opt/kafka/plugins/sink-connect-postgresql/0ec1ee34
