apiVersion: batch/v1
kind: Job
metadata:
  name: job-setup-postgres-table-offline
  namespace: kafka
spec:
  parallelism: 1
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        app: setup-postgres-table-online
    spec:
      containers:
      - name: setup-postgres-table-online
        image: majinetudacitylearn/postgres-cli:v0.0.1
        command:
          - "psql"
          - "-h"
          - "postgresql.default.svc.cluster.local"
          - "-p"
          - "5432"
          - "-U"
          - "feast_online"
          - "-d"
          - "feast_online"
          - "-f"
          - "config/create_table_online.sql"
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-online-secret
              key: password
        imagePullPolicy: Always
      restartPolicy: Never
  backoffLimit: 0