apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server-sample
  namespace: elastic-system
spec:
  version: 8.8.0
  count: 1
  elasticsearchRef:
    name: es-cluster
  kibanaRef:
    name: kibana-sample