apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es-cluster
  namespace: elastic-system
spec:
  version: 8.8.0
  volumeClaimDeletePolicy: DeleteOnScaledownOnly
  nodeSets:
    - name: masters
      count: 1
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
            storageClassName: microk8s-hostpath
            volumeMode: Filesystem
      config:
        # On Elasticsearch versions before 7.9.0, replace the node.roles configuration with the following:
        # node.master: true
        node.roles: [ "master" ]
        xpack.ml.enabled: true
        #node.remote_cluster_client: false
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
    - name: data
      count: 4
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
            storageClassName: microk8s-hostpath
            volumeMode: Filesystem
      config:
        # On Elasticsearch versions before 7.9.0, replace the node.roles configuration with the following:
        # node.master: false
        # node.data: true
        # node.ingest: true
        # node.ml: true
        # node.transform: true
        node.roles: [ "data", "ingest", "ml", "transform" ]
        #node.remote_cluster_client: false
      podTemplate:
        spec:
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
                runAsUser: 0
              command: [ 'sh', '-c', 'sysctl -w vm.max_map_count=262144' ]
          containers:
            - name: elasticsearch
