apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: logstash-sample
  namespace: elastic-system
spec:
  count: 1
  elasticsearchRefs:
    - name: es-cluster
      namespace: elastic-system
      clusterName: es-cluster
  version: 8.8.0
  pipelines:
    - pipeline.id: main
      pipeline.workers: 1
      config.string: |
        input {
          kafka {
            bootstrap_servers => "my-cluster-kafka-bootstrap.kafka:9092"
            topics => ["filebeat"]
            codec => json
          }
        }
        output {
          elasticsearch {
            hosts => ["10.64.140.43:9200"]
            manage_template => false
            index => "%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}"
            user => "elastic"
            password => "5l2J0rO1cEZnOwvO6064ry62"
          }
        }