apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: logstash-sample
  namespace: elastic-system
spec:
  count: 1
  elasticsearchRefs:
    - name: es-cluster
      namespace: elastic-system
  version: 8.8.0
  pipelines:
    - pipeline.id: main
      config.string: |
        input {
          kafka {
            bootstrap_servers => "my-cluster-kafka-bootstrap.kafka:9092"
            topics => ["filebeat"]
            codec => json
          }
        }
        output {
          elasticsearch {
            hosts => ["es-cluster-es-http.elastic-system:9200"]
            manage_template => false
            index => "%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}"
            user => "elastic"
            password => "x49886qXcCN23kg7PiQH9KS1"
          }
        }