kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: authservice-pvc
  namespace: istio-system
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 500Mi