CREATE ROLE repl_user REPLICATION LOGIN;
CREATE ROLE REPLICATION_GROUP;
GRANT REPLICATION_GROUP TO feast;
GRANT REPLICATION_GROUP TO repl_user;
ALTER TABLE titanic_survive_svc_v1 OWNER TO REPLICATION_GROUP;