apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: istio-ingressgateway
  namespace: kubeflow
spec:
  rules:
  - host: 10.64.140.43.nip.io
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: istio-ingressgateway-workload
            port:
              number: 80
