apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: kafka
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CiAgICAgICJhdXRoIjogImJXRnFhVzVsZEhWa1lXTnBkSGxzWldGeWJqcGtZMnR5WDNCaGRGODBOMUpXWjJWelVWSkJXa05mVmtJdGVWaDBRa3BhWTFKQk1tYz0iCiAgICB9CiAgfQp9Cg==
type: kubernetes.io/dockerconfigjson