name: Build Docker images

on:
  workflow_dispatch:
  #push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9" ]
    environment: development

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push (postgres Client)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: postgresSQL/Dockerfile-postgres
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/postgres-cli:v0.0.1
      - name: Build and push (kafka sink connector - postgres camel)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: postgresSQL/Dockerfile-kafka_sink_connector_postgres_camel.yaml
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/camel-postgresql-sink-kafka-connector:3.20.3.final