name: configurate Kafka

on:
  workflow_dispatch:

jobs:
  config_kafka:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v3
      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: 'ubuntu'
          server: ${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
          ssh_private_key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          local_path: './kafka/*'
          remote_path: '/home/ubuntu/kafka'
          sftpArgs: '-o ConnectTimeout=5'

      - name: setup Kafka Connector Cluster with Postgres plugin
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
          username: ${{ vars.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            kubectl apply -f kafka/KafkaConnect/debezium_postgres_connector.yaml

      - name: Sleep for 180 seconds
        uses: whatnick/wait-action@master
        with:
          time: '180s'
      - name: setup Postgres Connector for CDC
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
          username: ${{ vars.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            kubectl apply -f kafka/KafkaConnect/debezium_connector_progres.yaml