name: configurate Kafka

on:
  workflow_dispatch:

jobs:
  config_kafka:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v3
      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: 'ubuntu'
          server: ${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
          ssh_private_key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          local_path: './microk8s/*'
          remote_path: '/home/ubuntu/microk8s'
          sftpArgs: '-o ConnectTimeout=5'
      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: 'ubuntu'
          server: ${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
          ssh_private_key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          local_path: './kafka/*'
          remote_path: '/home/ubuntu/kafka'
          sftpArgs: '-o ConnectTimeout=5'
      - name: setup service account, secret, role, rolebinding for debezium connect cluster
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
          username: ${{ vars.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            kubectl apply -f microk8s/secrets/docker_secret.yaml
            kubectl apply -f microk8s/secrets/debezium_secret.yaml
            kubectl apply -f microk8s/secrets/postgresql_online_secret.yaml
            kubectl apply -f microk8s/serviceaccounts/debezium_connect_cluster_connect.yaml
            kubectl apply -f microk8s/serviceaccounts/kafka-connect-sink-postgres-cluster-connect.yaml
            kubectl apply -f microk8s/roles/connector_configuration_role.yaml
            kubectl apply -f microk8s/roles/connector_configuration_role_binding.yaml
      - name: Sleep for 60 seconds
        uses: whatnick/wait-action@master
        with:
          time: '60s'
      - name: run jobs to create tables
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
          username: ${{ vars.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            kubectl apply -f microk8s/jobs/postgresql/setup_table_offline.yaml
            kubectl apply -f microk8s/jobs/postgresql/setup_table_online.yaml
      - name: setup Kafka Connector Cluster with Postgres plugin
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
          username: ${{ vars.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            kubectl apply -f kafka/KafkaConnect/debezium_postgres_connector.yaml
            kubectl apply -f kafka/KafkaConnect/kafka_connect_sink_postgres.yaml

      - name: Sleep for 180 seconds
        uses: whatnick/wait-action@master
        with:
          time: '180s'
      - name: setup Postgres Connector for CDC
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
          username: ${{ vars.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            kubectl apply -f kafka/KafkaConnector/debezium_connector_progres.yaml
            kubectl apply -f kafka/KafkaConnector/postgres_sink_connector.yaml