name: Configure microk8s

on:
  workflow_dispatch:

jobs:
  config_default:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: configure group
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
          username: ${{ vars.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            microk8s kubectl create namespace kubeflow
            microk8s kubectl apply -f microk8s/config/memory-defaults.yaml --namespace=kubeflow
            microk8s kubectl apply -f microk8s/config/cpu-defaults.yaml --namespace=kubeflow
            microk8s kubectl apply -f microk8s/config/hard-mem-cpu.yaml --namespace=kubeflow
            microk8s kubectl apply -f microk8s/config/quota-pod.yaml --namespace=kubeflow
            
            microk8s kubectl apply -f microk8s/config/network_policy/deny-all.yaml
            microk8s kubectl apply -f microk8s/config/network_policy/allow-svc-kubernetes-for-kubeflow.yaml
            
            microk8s kubectl apply -f microk8s/config/network_policy/advertis-external-ip.yaml