name: Provisioning db

on:
  workflow_dispatch:

jobs:
  setup_db:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v3
      - name: Sleep for 60 seconds
        uses: whatnick/wait-action@master
        with:
          time: '60s'
      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: 'ubuntu'
          server: ${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
          ssh_private_key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          local_path: './postgresSQL/*'
          remote_path: '/home/ubuntu/postgresSQL'
          sftpArgs: '-o ConnectTimeout=5'
      - name: provisioning PostgreSQL
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
          username: ${{ vars.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            microk8s helm3 repo add bitnami https://charts.bitnami.com/bitnami
            microk8s helm3 install postgresql -f postgresSQL/config/values.yaml bitnami/postgresql

      - name: provisioning redis
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
          username: ${{ vars.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            microk8s helm3 install "redis" bitnami/redis

