name: Provisioning kafka

on:
  workflow_dispatch:

jobs:
  setup_kafka:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v3
      - name: install Strimzi Operator
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
          username: ${{ vars.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            kubectl create namespace kafka
            kubectl create -f 'https://strimzi.io/install/latest?namespace=kafka' -n kafka
      - name: Sleep for 180 seconds
        uses: whatnick/wait-action@master
        with:
          time: '180s'
      - name: Create an Apache Kafka cluster
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
          username: ${{ vars.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            # Apply the `Kafka` Cluster CR file
            kubectl apply -f https://strimzi.io/examples/latest/kafka/kafka-persistent-single.yaml -n kafka
            kubectl wait kafka/my-cluster --for=condition=Ready --timeout=300s -n kafka