name: Provisioning log monitoring

on:
  workflow_dispatch:

jobs:
  setup_kafka:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v3
      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: 'ubuntu'
          server: ${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
          ssh_private_key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          local_path: './eck/*'
          remote_path: '/home/ubuntu/eck'
          sftpArgs: '-o ConnectTimeout=5'
      - name: install ECK (Elastic Cloud on Kubernetes)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
          username: ${{ vars.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            
            # Install Elasticsearch by eck
            kubectl create -f https://download.elastic.co/downloads/eck/2.8.0/crds.yaml
            
            # Install the Elastic operator
            kubectl apply -f https://download.elastic.co/downloads/eck/2.8.0/operator.yaml
            
            # Deploy Elasticsearch
            kubectl apply -f eck/config/elasticsearch.yaml
            # Deploy Kibana
            kubectl apply -f eck/config/kibana.yaml
            # Deploy apm-server
            kubectl apply -f eck/config/apmserver.yaml

      - name: Sleep for 3 minutes
        uses: whatnick/wait-action@master
        with:
          time: '3m'
      - name: install ECK (Elastic Cloud on Kubernetes)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
          username: ${{ vars.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            # Deploy beats
            kubectl apply -f eck/config/beat.yaml
            # Deploy logstash
            kubectl apply -f eck/config/logstash.yaml
            
            
            
           
