name: Setup Kubernetes Cluster and worker node

on:
  workflow_dispatch:

jobs:
  setup_cluster_and_worker:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v3
      - name: setup cluster
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
          username: ${{ vars.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            sudo kubeadm init --pod-network-cidr=192.168.0.0/16 --ignore-preflight-errors=NumCPU,Mem
            
            mkdir -p $HOME/.kube
            sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
            sudo chown $(id -u):$(id -g) $HOME/.kube/config
            
            kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/tigera-operator.yaml
            kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/custom-resources.yaml
            
            kubectl taint nodes --all node-role.kubernetes.io/control-plane-
            
            kubectl apply -f https://projectcontour.io/quickstart/contour.yaml

      - name: deploy metric server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
          username: ${{ vars.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            kubectl apply -f metric-server/config/components.yaml

      - name: deploy prometheus
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
          username: ${{ vars.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            kubectl apply -f prometheus/config/ns_monitoring.yaml
            
            export SERVER_IP=${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
            envsubst < prometheus/config/pv-pvc.yaml | kubectl apply -f -
            
            kubectl apply -f prometheus/config/cluster-role.yaml
            kubectl apply -f prometheus/config/service-account.yaml
            kubectl apply -f prometheus/config/cluster-role-binding.yaml
            
            kubectl apply -f prometheus/config/configmap.yaml
            kubectl apply -f prometheus/config/deployment.yaml
            kubectl apply -f prometheus/config/service.yaml
            
            kubectl apply -f prometheus/config/kube-state-metrics.yml

      - name: get join command for worker node
        id: get_join_command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
          username: ${{ vars.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            join_command=$(echo "join_command=kubeadm token create --print-join-command")
            echo "::set-output name=join::join_command"

      - name: join worker node to cluster
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.AWS_EC2_WORKER_NODE_1_IP }}
          username: ${{ vars.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            sudo ${{ steps.get_join_command.outputs.join }}