name: Setup Kubernetes Worker node

on:
  workflow_dispatch:

jobs:
  setup_k8s_cluster_in_worker_node:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v3
      - name: setup cluster
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
          username: ${{ vars.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            sudo kubeadm join 172.30.4.241:6443 --token 096ysy.v6y1vtiflpao2pqp --discovery-token-ca-cert-hash sha256:7a98782e06ac38bd29dcab6459b58aab7b27f593314819c47ae20adb0ebe1e01
