name: setup Service accounts, Secrets, Roles, and RoleBinding

on:
  workflow_dispatch:

jobs:
  setup_sa_secrets:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v3
      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: 'ubuntu'
          server: ${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
          ssh_private_key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          local_path: './microk8s/*'
          remote_path: '/home/ubuntu/microk8s'
          sftpArgs: '-o ConnectTimeout=5'
      - name: setup service account and secret for minio
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
          username: ${{ vars.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            kubectl apply -f microk8s/secrets/minio_secret.yaml
            kubectl apply -f microk8s/serviceaccounts/sa_minio_fullaccess_default.yaml
            
            kubectl apply -f microk8s/secrets/debezium_secret.yaml
            kubectl apply -f microk8s/serviceaccounts/debezium_connect_cluster_connect.yaml
            kubectl apply -f microk8s/roles/connector_configuration_role.yaml
            kubectl apply -f microk8s/roles/connector_configuration_role_binding.yaml