name: setup Service accounts and Secrets

on:
  workflow_dispatch:

jobs:
  setup_sa_secrets:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v3
      - name: setup service account and secret for minio
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
          username: ${{ vars.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            kubectl apply -f microk8s/secrets/minio_secret.yaml
            kubectl apply -f microk8s/serviceaccounts/sa_minio_fullaccess_default.yaml