name: setup Charmed kubeflow

on:
  workflow_dispatch:

jobs:
  setup_kubeflow:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v3
      - name: install juju and kubeflow
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
          username: ${{ vars.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            sudo snap install juju --classic
            juju bootstrap microk8s
            juju add-model kubeflow
            
            juju deploy kubeflow --trust  --channel=1.4/stable

      - name: clear memory cache
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
          username: ${{ vars.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            sudo sh -c 'echo 3 > /proc/sys/vm/drop_caches'

      - name: Sleep for 1500 seconds
        uses: whatnick/wait-action@master
        with:
          time: '1500s'

      - name: clear memory cache
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
          username: ${{ vars.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            sudo sh -c 'echo 3 > /proc/sys/vm/drop_caches'

      - name: check running status
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
          username: ${{ vars.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            kubectl wait --for=jsonpath='{.status.phase}'=Running --timeout=2400s pod --all -n kubeflow
            
            microk8s enable metallb:"10.64.140.43-10.64.140.49"

      - name: configuration
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
          username: ${{ vars.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            juju config dex-auth public-url=http://10.64.140.43.nip.io
            juju config oidc-gatekeeper public-url=http://10.64.140.43.nip.io
            juju config dex-auth static-username=admin
            juju config dex-auth static-password=admin