name: setup Charmed kubeflow

on:
  workflow_dispatch:

jobs:
  setup_kubeflow:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v3
      - name: installation
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.AWS_EC2_CONTROL_PLANE_IP }}
          username: ${{ vars.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            sudo snap install juju --classic
            juju bootstrap microk8s
            juju add-model kubeflow
            
            juju deploy kubeflow --trust  --channel=1.6/stable